spring:
  jpa:
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://{URL}/stakanto
    username: ${USERNAME}
    password: ${PASSWORD}
jwt:
  secret: ${SECRET}
  expired:
    access: 1800
    refresh: 43200
server:
  port: 8080