spring:
  jpa:
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    password: ${PASSWORD}
    url: ${URL}
    username: ${USERNAME}
jwt:
  secret: ${SECRET}
  expired:
    access: ${ACCESS_TOKEN_EXPIRED}
    refresh: ${REFRESH_TOKEN_EXPIRED}